/**
 * OE Network — Visit / Calling Log form (public, mobile-first).
 *
 * Replaces the Google Form the OEM salespeople use. Opened via a shared link;
 * no login, no dashboard — just a splash and the form. Reps fill this on
 * phones, so the layout is single-column, touch targets are >=48px and every
 * input uses a >=16px font (anything smaller makes iOS Safari zoom on focus).
 *
 * Conditional behaviour (per spec):
 *   • Mats Sales  — every OEM except MSIL (MSIL reports channel instead)
 *   • Photo       — only when the contact mode is "Visit" (gallery only)
 *   • Email       — derived from the chosen name, submitted silently
 *   • City        — filtered by the chosen State
 *   • Dealership  — searchable, filtered by State
 *   • Remarks     — pick 1+ categories, each opens its own note; combined into
 *                   the single Remarks cell the sheet already has.
 *
 * Field names mirror the headers the OE log-book sync reads
 * (services/oe_network_sync.py :: LOG_COLUMNS) so submissions stay compatible
 * with the existing sheet + sync.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertCircle,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ImagePlus,
  Loader2,
  MapPin,
  MessageSquare,
  Plus,
  Search,
  Send,
  TrendingUp,
  User,
  X,
} from "lucide-react";

const logoSrc = "/amato-logo.png";
const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

// Keyless public API for Indian states + their cities.
const GEO_STATES_URL =
  "https://countriesnow.space/api/v0.1/countries/states/q?country=India";
const GEO_CITIES_URL =
  "https://countriesnow.space/api/v0.1/countries/state/cities/q?country=India&state=";

// ─── Option data ─────────────────────────────────────────────────────────────
// Salesperson → email. The rep only picks a name; the address rides along with
// the submission (never shown, never typed) so the sheet's email column always
// matches the person. Per-person sheet access is keyed on this.
const SALESPERSON_EMAILS: Record<string, string> = {
  "UMESH KALE": "umeshkale@autoformindia.com",
  "DEBASIS BEHERA": "debasis@autoformindia.com",
  "ASHOKA": "ashoka@autoformindia.com",
  "D PRASHANTH KUMAR": "prashanth@autoformindia.com",
  "PANKAJ VIG": "pankaj@autoformindia.com",
  "DURGESH": "durgesh@autoformindia.com",
};
const SALESPEOPLE = Object.keys(SALESPERSON_EMAILS);

const OEMS = ["KIA", "MSIL", "HYUNDAI", "TATA", "MAHINDRA"];
const CONTACT_MODES = ["Visit", "Calling"];

/** MSIL is handled specially: it reports the dealership's channel (Arena / Nexa,
 *  asked right under the OEM) and does NOT report mats. Every other OEM reports
 *  monthly mats and has no channel. */
const MSIL = "MSIL";
const MSIL_CHANNELS = ["Arena", "Nexa"];

const REMARK_CATEGORIES = ["Product Feedback", "Replacement", "Sales", "Others"];
// "Product Feedback" -> "product_feedback" — the form-field / backend key for
// this category's own column. Keep in sync with the backend's Form(...) params.
const remarkKey = (c: string) => c.toLowerCase().replace(/[^a-z0-9]+/g, "_");

/** A dealer as the dropdown deals with it. `city` is "" when we don't know it
 *  yet — the OEMs whose dealer file hasn't arrived (TATA, HYUNDAI, KIA,
 *  MAHINDRA) are all city-less for now, and those fall back to the rep picking
 *  a city by hand. */
type DealerOption = { name: string; city: string };

/** The offline fallback below holds bare names; the API sends {name, city}. */
const asOptions = (list: (string | DealerOption)[]): DealerOption[] =>
  list.map((d) => (typeof d === "string" ? { name: d, city: "" } : d));

/** A group can run several outlets and the city is the only thing separating
 *  them (PREM MOTORS Narela vs PREM MOTORS Wazirpur), so the rep has to be
 *  choosing between cities, not names. Only the name is written to the sheet;
 *  the city goes to the City field. */
const dealerLabel = (d: DealerOption) => (d.city ? `${d.name} — ${d.city}` : d.name);

// Dealership master list, keyed by OEM then by the geo API's state names (so
// it lines up with the State field). Dealers differ per OEM, so the dropdown
// needs BOTH the OEM and the State chosen.
// TODO(data): only MSIL is populated; the other OEMs' lists are pasted in below.
const DEALERSHIPS_BY_OEM_STATE: Record<string, Record<string, string[]>> = {
  MSIL: {
  "Andaman and Nicobar Islands": ["RUKMANI MOTORS"],
    "Andhra Pradesh": ["BHARGAVI", "JAYABHERI AUTOMOTIVES", "JAYALAKSHMI AUTOMOBILES", "M.S.A. MOTORS", "NIVYA AUTOMOBILES", "NOVELTY REDDY & REDDY MOTORS", "REDDY & REDDY MOTORS", "S B MOTOR CORPORATION", "SANTOSH AUTOMOTORS", "SATTI BABU MOTORS", "VARUN MOTORS"],
    "Arunachal Pradesh": ["D Y MOTORS"],
    "Assam": ["BAJRANG CAR WORLD", "BHARATI MOTORS", "BIMAL AUTO AGENCY", "JAINCO", "JAY BEE AUTO AGENCIES", "MITTAL AUTO ZONE", "PALLAVI MOTORS", "PODDAR CAR WORLD", "RD MOTORS", "SAIKIA AUTO", "VISHAL CAR WORLD"],
    "Bihar": ["ALANKAR AUTO", "DMC CARS", "GS MOTORS", "HORIZON AUTOMOBILES", "KARLO AUTOMOBILES", "PEARL CARS", "RAJIV AUTOMOBILES", "RAJKRISHNA MOTORS", "RAMKRSIHNA MOTORS", "REESHAV AUTOMOBILES", "SEEMANCHAL MOTORS", "SHREE GOPAL AUTO"],
    "Chhattisgarh": ["CHOUHAN AUTOMOBILES", "HDN MOTORS", "M SQUARE MOTORS", "MAHAMAYA AUTO CARS", "SATYA AUTOMOBILES", "SKY AUTOMOBILES", "SPARSH AUTO", "VISHWABHARTI AUTOMOBILES"],
    "Delhi": ["AAA VEHICLEADES", "COMPETENT", "D D MOTORS", "MAGIC AUTO", "PREM MOTORS", "RANA MOTOR", "ROHAN MOTORS", "SAYA AUTOMOBILES", "SHREYASH AUTOMOTIVES", "SINGLA LINK AGENCY", "T R SAWHNEY"],
    "Goa": ["CHOWGULE", "SAI POINT CARS PVT LTD", "SAI SERVICE"],
    "Gujarat": ["ALPHA AUTOLINK", "AMAR CARS", "ATUL MOTOR", "B. M. AUTOLINK", "COMET MOTORS", "DHRU", "DREAMVEHICLES", "K D MOTORS", "KATARIA AUTOMOBILES", "KIRAN MOTOR", "NANDA AUTOMOBILES", "PEGASUS", "PERFECT AUTO SERVICE", "POPULAR WHEELERS", "RAVIRATNA MOTORS", "RB CARS", "STARLINE CARS", "TANU MOTORS", "UDAY AUTOLINK", "VIMCO MOTORS"],
    "Haryana": ["AUTO GALLERY", "AUTO NATION", "AUTO VIBES LLP", "AUTOVOUGE", "DINCO 4 WHEELS", "EAKANSH MOTORS", "FAIR DEAL CARS", "JAGMOHAN MOTOR", "KARNAL MOTORS", "PASCO AUTOMOBILES", "PLATINUM MOTOCORP", "SARAOGI AUTOMOBILES", "SHAKTI MOTORS", "SWASTIK MOTOCORP", "TCS & ASSOCIATES", "UNIQUE AUTOLEAD"],
    "Himachal Pradesh": ["COMPETENT", "GOYAL MOTORS"],
    "Jammu and Kashmir": ["COMPETENT", "JAMKASH VEHICLEADES", "JAMKASH VEHICLEADES (KASHMIR)", "JAMMU MOTORS", "KANGRA VEHICLEADES", "KATHROO MOTORS", "NSF VEHICLES", "PEAKS AUTO"],
    "Jharkhand": ["CAR ONE", "HILLTOP MOTORS", "HINDUSTAN AUTO AGENCY", "MOTOR WORLD", "PEBCO MOTORS", "PREMSONS MOTOR UDYOG", "RELIABLE INDUSTRIES", "TULSYAN MOTOR"],
    "Karnataka": ["ABHARAN MOTORS", "AVANISH MOTORS", "BHARATH AUTO CARS", "BIMAL AUTO AGENCY", "K.P.F. PVT. LTD.", "KALYANI MOTORS", "KATARIA AUTOMOBILES", "LAHOTI MOTORS", "MANDOVI MOTORS", "MUNEER CARS", "POPULAR VEHICLES", "PRATHAM MOTORS", "PRN AUTOMOTIVE", "REVANKAR MOTOR", "RNS MOTORS", "SAKETH AUTOMOBILES", "SANVIT AUTOMOTIVES LLP", "SHANTESHA MOTORS", "SHRUTI MOTORS", "SREE LAKSHMI", "SURAKSHA CAR", "VARUN MOTORS", "VENKAT MOTORS", "VIJAY MOTOWINGS"],
    "Kerala": ["A M MOTORS", "A.V.G.MOTORS", "BRD CAR WORLD", "GEORGE MAIJO", "INDUS MOTOR", "KVR AUTOCARS", "POPULAR VEHICLES", "SAI SERVICE", "SARATHY AUTO CARS"],
    "Ladakh": ["DRUK AUTO"],
    "Madhya Pradesh": ["ADINATH MOTORS", "CITY CARS", "DAGA MOTORS", "INFINITY CARS", "JEEWAN MOTORS", "KAMTHI MOTORS", "KATHED MOTOCORP", "KTL AUTOMOBILES", "MAA GAYATRI AUTOMOBILES", "NIKUNJ MOTORS", "NIMAR MOTORS", "OCEAN MOTORS", "PANDYA AUTOMOBILES", "PATEL MOTORS", "PREM MOTORS", "RAJRUP MOTOR JUNCTION", "RANA MOTOR", "RUKMANI MOTORS", "SATYAM MOTORS", "SHUBH MOTORS", "SRISATYASAI AUTOMOBILES", "STANDARD AUTO", "UNITARA MOTORS", "YUG CARS"],
    "Maharashtra": ["AHER AUTOPRIME LLP", "ARUN MOTORS", "ARYA CARS", "ASPA BANDSONS AUTO", "AUTOMOTIVE MANUFACTURERS", "AUTOMOTIVE MANUFACTURERS PVT. LTD.", "CHAVAN", "CHOWGULE", "EXCEL AUTOVISTA", "FORT POINT AUTOMOTIVE", "HIMALAYA CARS", "JAGRUT MOTORS", "KANKARIYA AUTOMOBILES", "KHANDELWAL AUTOWHEELS", "KHANDESH MOTORS LLP", "KOTHARI WHEELS", "KR MOTORS KOLKOHUR", "MAHALAXMI AUTOMOTIVES", "MANRAJ AUTOMOBILES", "MY CAR", "NAVNIT MOTORS", "PAGARIYA AUTO", "SAI SERVICE", "SARAYU INVESTMENT", "SEHGAL AUTORIDERS", "SEVA AUTOMOTIVE", "SHAAN CARS", "SHIVAM AUTO ZONE", "SIDDHI WHEELS", "SIMRAN MOTORS", "SUMAN KIRTI CAR", "SUPREME AUTOMOBILES", "TRISTAR", "VELOX MOTORS", "VITESSE PVT LTD", "WONDER CAR"],
    "Manipur": ["EASTERN MOTORS", "SAMADON ENTERPRISE"],
    "Meghalaya": ["BANALARI WORLD CARS", "RANI MOTORS"],
    "Mizoram": ["GIG MOTORS"],
    "Nagaland": ["PROGRESSIVE MOTORS", "SEYIE AUTO"],
    "Odisha": ["APARNAA MOTORS", "JYOTE MOTORS", "LEGEND CARS", "NARAYANI MOTORS", "ODYSEY", "ORBIT MOTORS", "SKY AUTOMOBILES", "TUSHI MOTORS"],
    "Punjab": ["AUTOPACE", "BABA AUTO", "CM AUTO SALES", "CM AUTOMOBILES", "GULZAR MOTOR", "HIRA AUTOMOBILE", "HOSHIARPUR AUTOMOBILES", "JAYCEE MOTORS", "JUJHAR MOTOR", "LOVELY AUTOS", "MAPSKO AUTO INDIA", "MARWAH AUTOS", "MAX AUTO", "MODERN AUTOMOBILES", "NAVDESH AUTOS", "PATHANKOT VEHICLEADES", "PLUTON DREAMWORKS", "REMIRA MOTORS", "SWANI MOTORS", "TARA AUTOMOBILES", "TRICITY AUTOS"],
    "Rajasthan": ["AJMER AUTO", "AURIC MOTORS", "BHATIA AND COMPANY", "CHAMPION CARS", "DUDI AUTOMOBILES", "FORTUNE CARS", "JAMU AUTOMOBILES", "K.P. AUTOMOTIVES", "KTL PVT. LTD.", "LMJ SERVICES", "M.G. MOTORS", "NAVNEET MOTORS", "PREM MOTORS", "RELAN MOTORS", "SANGA AUTONATION", "SATNAM MOTOCORP", "SHRI KRISHNA AUTOSALES", "SHRI MANGALAM AUTO", "SUWALKA MOTORS", "TECHNOY", "TM MOTORS", "VIPUL MOTORS"],
    "Sikkim": ["ENTEL MOTORS"],
    "Tamil Nadu": ["A.I.ENTERPRISES", "AADHI CARS", "ABT LIMITED", "ASIR AUTOMOBILES", "ATHEN CARS", "CARS INDIA PVT. LTD.", "CRESCO", "GANESH CARS", "JAI KRISHNAA AUTOSALES", "KHIVRAJ MOTORS", "MEENAKSHI AUTO ZONE", "PILLAI & SONS MOTOR COMPANY", "PLA MOTORS", "POPULAR VEHICLES", "RAJALAKSHMI CARS", "S M CAR", "SHENBAKA CARS", "SIVA AUTOMOTIVE TRADING", "SRE SHASHTI CAR", "SREE SARADHAMBAL AUTOMOBILES", "SRI AMMAN CARS", "SRI CITY AUTO", "THRIVENI CAR", "VISHNU CARS"],
    "Telangana": ["ACER MOTORS", "ADARSHA AUTO WORLD", "AUTOFIN LIMITED", "GEM MOTORS (INDIA)", "JAYABHERI AUTOMOTIVES", "MITHRA AUTO AGENCIES", "PAVAN MOTORS", "POPULAR VEHICLES", "SAI SERVICE", "SRI JAYARAMA MOTORS", "WIN MOTORS"],
    "Tripura": ["JAIN UDYOG", "PALLAVI MOTORS"],
    "Uttar Pradesh": ["AGR AUTOMOBILES", "AKANKSHA AUTOMOBILES", "AMITDEEP MOTORS", "ANAND MOTOR", "ANIL MOTORS", "ARBIT AUTOMOBILES", "BRIGHT 4 WHEEL SALES", "BRIGHT 4 WHEEL SALES PRAYAGRAJ", "CONCEPT CARS", "CORAL MOTORS", "DEEP MOTORS", "DEV MOTORS", "FAIR DEAL CARS", "GLOBUS", "KAVISHA MOTORS", "KIRTIKUNJ AUTOMOBILES", "KTL PVT. LTD.", "KULDEEP MOTORS", "MEGA MOTORS", "MERAK VEHICLES", "MOTORCRAFT INDIA", "MY CAR", "NANDANI MOTORS", "ONE UP MOTORS INDIA", "PREM MOTORS", "RADHA GOVIND AUTOMOBILES", "REGENT AUTOMOBILES", "SARASWATI MOTORS", "SB CARS", "SKUNIVERSE AUTOMOBILE", "SMARTWHEELS", "SNV AUTOMOBILES", "STAR CARS", "SUMITRA DS MOTORS", "SURI AUTOMOBILES", "TANYA AUTOMOBILES", "UMA MOTORS", "VARANASI MOTORS", "VELOCITY CARS", "VIPUL MOTORS"],
    "Uttarakhand": ["AKANKSHA AUTOMOBILES", "D D MOTORS", "FUTURE AUTO WHEELS", "NAINITAL MOTORS", "PREM MOTORS", "ROHAN MOTORS", "SHAKUMBARI AUTOMOBILES"],
    "West Bengal": ["BEE KAY AUTO", "BHANDARI", "DEWARS GARAGE", "J.K. WHEELS", "JYOTE MOTORS (BENGAL)", "MACHINO TECHNO (SALES)", "ONE AUTO", "OSL MOTOCORP", "PODDAR CAR WORLD", "PREMIER CAR WORLD", "SAINATH AUTOLINKS", "SANEI MOTORS", "SEVOKE MOTORS", "STARBURST MOTORS", "SWG CAR WORLD"],
  },
  KIA: {
    "Andhra Pradesh": ["CASA KIA", "HOSHI KIA", "KANTIPUDI KIA", "LAKSHMI KIA", "MG KIA", "SHANKAR RAO KIA", "SIMHA KIA"],
    "Arunachal Pradesh": ["NIGLA KIA"],
    "Assam": ["BORAH KIA", "DIVINE KIA", "FOTUNE KIA", "GOYAL KIA", "INFINITY KIA", "MERIDIAN KIA"],
    "Bihar": ["AMARJYOTI KIA", "BUDHAV KIA", "GOBERDHAN KIA", "KOSI KIA", "MAVRA KIA", "PREMA KIA", "RAJ KIA"],
    "Chandigarh": ["JOSHI KIA"],
    "Chhattisgarh": ["INTARA KIA", "KRISHNA KIA", "MAHADEVA KIA", "MAHAMAYA KIA", "MASOJI KIA", "SAIRAM KIA"],
    "Delhi": ["ALLIED KIA", "ALLIED KIA CP", "AUTOMOTIVE KIA", "FRONTIER KIA", "JAYANTI KIA", "JAYANTI MOTORS", "LOHIA KIA", "MALWA KIA", "PREFERRED DEALER AUTOMOTIVE KIA", "RITU KIA", "SHUBAN SAI", "SPARSH KIA", "SPEEDINGO KIA"],
    "Goa": ["ADC KIA VERNA", "AUTOMOTIVEIS DE CRISTAL"],
    "Gujarat": ["BM KIA", "DESTINATION KIA", "GALLOPS KIA", "GOPINATHJI KIA", "HALLEYS KIA", "HIVAM KIA", "PARIN KIA", "RATHOD KIA", "SHIVAM KIA", "SHREENATH CARS KIA", "SHREENATH KIA", "SUPERNOVA KIA", "SURAT KIA", "VIBRANT KIA", "WEST KIA", "WESTCOAST KIA", "WESTERN KIA"],
    "Haryana": ["ALLIED MOTORS", "ASB KIA", "DHINGRA MOTORS", "FRONTIER KIA"],
    "Jharkhand": ["DILLIP KIA", "ELEGEN KIA", "HORIZON KIA", "JUHI KIA", "REPULIC KIA", "UTKAL KIA"],
    "Karnataka": ["ADVAITH KIA", "EPITOME KIA", "JANSI KIA", "MIRACULUM KIA", "NAARA KIA", "NAGSHANTI KIA", "PPS KIA", "TAAPASI", "VST KIA"],
    "Kerala": ["AUTOMOTIVE KIA", "DKH KIA", "INCHEON KIA"],
    "Madhya Pradesh": ["ABHISHEK KIA", "BADERIYA KIA", "BHAGIRATH KIA", "KHATWANI KIA", "ROYAL KIA", "SARVAGYA KIA", "SETH KIA", "SHREE KIA", "SHRI KIA", "SNR KIA", "SOMYA KIA", "UPDESH KIA"],
    "Maharashtra": ["AJINKYA KIA", "AKSHAY KIA", "AMAN KIA", "ARYODAYA KIA", "AUTOBAHN KIA", "BHAVNA KIA", "CELEBRATE KIA", "CRYSTAL KIA", "DHONE KIA", "HIVAAY KIA", "JAIKA KIA", "JPS KIA", "KANSE KIA", "KHUSHI KIA", "KODUSKAR KIA", "KONDUSKAR KIA", "LATUR KIA", "MODI KIA", "PARSHV KIA", "PARVATI KIA", "PIPADA KIA", "RAC KIA", "SALASAR KIA", "SHREENATH KIA", "UNNAI KIA"],
    "Meghalaya": ["ACROPOLIS KIA"],
    "Odisha": ["BASANTI KIA", "CENTRAL KIA", "EMPREO KIA", "KRISHNA KIA", "MAJESTY KIA", "SANJIB KIA", "TRUPTI KIA"],
    "Rajasthan": ["ALLIED KIA", "ARAVALI KIA", "GALAXY KIA", "KUMBHAT", "KUMBHAT KIA", "MAHARIA KIA", "MEHER KIA", "MORVI KIA", "PARAS KIA", "RAJENDRA KIA", "RAJESH KIA", "RATAN KIA", "ROSHAN KIA", "SAMARDH KIA", "SANDEEP KIA", "SANGHI KIA", "WEST COAST KIA"],
    "Tamil Nadu": ["ARAS KIA", "ASJ KIA", "CAPITAL KIA", "KUN KIA", "PRESSANNA KIA", "RAMANI KIA", "SKMM KIA", "SVM KIA", "VST KIA"],
    "Telangana": ["AUTOMOTIVE KIA", "CAR KIA", "LANDMARK KIA", "MALIK KIA", "PROSPERA KIA", "PSR KIA", "SUNRISE KIA"],
    "Uttar Pradesh": ["ADYANT KIA", "ALLIED KIA", "ASB AUTOMOBILES", "ASB KIA", "AVANTIKA KIA", "BALA JI KIA", "BALAJI KIA", "BRIGHT KIA", "EMPIRE KIA", "GLOBAL KIA", "ICONIC KIA", "JAYANTI KIA", "KABIR KIA", "KARMA KIA", "KHANNA KIA", "LOHIA KIA", "NRL KIA", "PITAMBRA KIA", "PITANBRA KIA", "PREM KIA", "SAHIB KIA", "SAS KIA", "SHREE ASR KIA", "SHREE SHIV SHAKTI KIA", "SHRI SHIVA SHAKTI", "SHUBH KIA", "SHUBHAM KIA", "SKYDAC KIA", "SMART KIA", "SYKDAC KIA", "UNITED KIA", "VIRENDRA KIA"],
    "Uttarakhand": ["AVS KIA", "CLASSIC KIA", "SHUBH KIA"],
    "West Bengal": ["CELICA KIA", "EASTERN KIA", "GAJRAJ KIA", "GANGES KIA", "KANHA KIA", "KIA SALTLAKE", "LANDMARK KIA", "RUDRA KIA", "SHANVI KIA", "SPL KIA"],
  },
  HYUNDAI: {
    "Andhra Pradesh": ["KESHWIN HYUNDAI", "KUN HYUNDAI", "KUSULAVA", "LAKSHMI HYUNDAI", "LUCKY", "MANGO HYUNDAI", "RK HYUNDAI", "SAI SWARNA", "SRI CHAKRA HYUNDAI"],
    "Arunachal Pradesh": ["NENI HYUNDAI"],
    "Assam": ["AKASH HYUNDAI", "BORAH HYUNDAI", "KRISHNA HYUNDAI", "LOHIA HYUNDAI", "MANDONA HYUNDAI", "MUKESH HYUNDAI", "N K S HYUNDAI", "OJA HYUNDAI", "R J HYUNDAI", "SARAIGHAT HYUNDAI", "SINGHI HYUNDAI"],
    "Bihar": ["ASHIANA HYUNDAI", "ASMA HYUNDAI", "BALAJI HYUNDAI", "BINAY HYUNDAI", "IMPERIAL HYUNDAI", "KRRISH HYUNDAI", "LUMBINI HYUNDAI", "MAHAKALI HYUNDAI", "MUSAFIR HYUNDAI", "NIDHI HYUNDAI", "RADHA HARI HYUNDAI", "SAHIL HYUNDAI"],
    "Chandigarh": ["CHARISMA HYUNDAI", "ULTIMATE HYUNDAI"],
    "Chhattisgarh": ["KRISHNA HYUNDAI", "MANGALAM HYUNDAI", "SHANKARA HYUNDAI", "SHIVNATH HYUNDAI"],
    "Delhi": ["ASHOK HYUNDAI", "BAGGA LINK HYUNDAI", "DEEP HYUNDAI", "FRONTIER HYUNDAI", "HANS HYUNDAI", "HIMGIRI HYUNDAI", "KARMA HYUNDAI", "KONCEPT HYUNDAI", "LAMBA HYUNDAI", "M R HYUNDAI", "MALWA HYUNDAI", "PAHWA HYUNDAI", "RAMAA HYUNDAI", "ROYAL DREAM HYUNDAI", "SHUBAN SAI HYUNDAI", "SUNRISE HYUNDAI", "TRIUMPH HYUNDAI", "UNIVERSAL HYUNDAI", "VELOCITY HYUNDAI"],
    "Goa": ["GOA HYUNDAI", "SAIRAM HYUNDAI"],
    "Gujarat": ["ALDIAM HYUNDAI", "B MANGATRAM HYUNDAI", "BHURAWALA HYUNDAI", "CONCEPT HYUNDAI", "DIVINE HYUNDAI", "DOWNTOWN HYUNDAI", "EMINENT HYUNDAI", "EQUITY HYUNDAI", "GALLOPS HYUNDAI YMCA", "GANESH HYUNDAI", "KARNAVATI HYUNDAI NIKOL", "MONARCH HYUNDAI", "NAVJIVAN CARS PVT.LTD HYUNDAI", "NAVJIVAN HYUNDAI", "NAVJIVAN MOTOR", "NEO HYUNDAI", "OM HYUNDAI", "ORANGE HYUNDAI", "PATEL HYUNDAI", "PLANET HYUNDAI", "PRATHAM HYUNDAI", "PRESIDENT HYUNDAI", "PUNJAB HYUNDAI", "RIYA HYUNDAI", "RSA AUTOMOTIVES", "SANVI HYUNDAI", "SHARMA HYUNDAI", "SHIV HYUNDAI", "SHIVALIK HYUNDAI", "SP HYUNDAI", "VTEX HYUNDAI"],
    "Haryana": ["BAYERISCHE HYUNDAI", "DEE EMM HYUNDAI", "HARSH VARDHAN HYUNDAI", "JMV HYUNDAI", "KHANNA HYUNDAI", "PROFESSIONAL HYUNDAI", "RAHUL HYUNDAI", "SAFDARJANG HYUNDAI", "SAMRITHI HYUNDAI", "SAMTA HYUNDAI", "SAWAN HYUNDAI", "ULTIMATE HYUNDAI"],
    "Himachal Pradesh": ["BHAKRA HYUNDAI", "PUNJ HYUNDAI", "SANT HYUNDAI", "TAPAN HYUNDAI"],
    "Jammu and Kashmir": ["AM HYUNDAI", "DEVIKA HYUNDAI", "FAIRDEAL AUTO HYUNDAI", "HK HYUNDAI", "PACE HYUNDAI", "PLATINUM HYUNDAI", "SHUHUL HYUNDAI"],
    "Jharkhand": ["FAIRDEAL HYUNDAI", "J P HYUNDAI", "LIBRA HYUNDAI", "NEW WAVE HYUNDAI", "REPUBLIC HYUNDAI"],
    "Karnataka": ["ADVAITH HYUNDAI", "BLUE HYUNDAI", "KANCHANA HYUNDAI", "KJ HYUNDAI", "LAKSHMI HYUNDAI", "NAGSHANTI HYUNDAI", "PAVAN HYUNDAI", "TRIDENT HYUNDAI"],
    "Kerala": ["APCO HYUNDAI", "CLASSIC HYUNDAI", "KESHVIN HYUNDIA", "KVR HYUNDAI", "POPULAR HYUNDAI", "VTJ HYUNDAI"],
    "Madhya Pradesh": ["ABHISHEK HYUNDAI", "ANMOL HYUNDAI", "ASM HYUNDAI", "BABA HYUNDAI", "BADRIKA HYUNDAI", "CI HYUNDAI", "GUPTA HYUNDAI", "HARSH HYUNDAI", "HARSHALI HYUNDAI", "KASLIWAL HYUNDAI", "PRESTIGE HYUNDAI", "PRINCE HYUNDAI", "ROYAL HYUNDAI", "SRISHTI HYUNDAI", "STARLINE HYUNDAI", "SUNSHINE HYUNDAI", "SURJEET HYUNDAI"],
    "Maharashtra": ["ARSH HYUNDAI", "BHUVAN HYUNDAI", "BIGWIG HYUNDAI", "DEEP HYUNDAI", "EROS HYUNDAI", "FOCUS HYUNDAI", "GANDHI HYUNDAI", "GARVE HYUNDAI", "ILAKSHI HYUNDAI", "INDEX HYUNDAI", "ISHANYA HYUNDAI", "JAYA HYUNDAI", "KAMAL HYUNDAI", "KANASE HYUNDAI", "KANKARIA HYUNDAI", "KETAN HYUNDAI", "KOTHARI HYUNDAI", "KUNDAN HYUNDAI", "LAKHANI AUTOMOTIVE", "MAI HYUNDAI", "MIRA HYUNDAI", "MITTAL HYUNDAI", "MODI HYUNDAI", "NAVKAR HYUNDAI", "PRABH HYUNDAI", "R R KIRAD HYUNDAI", "RADIANT HYUNDAI", "SAI AUTO HYUNDAI", "SANJAY HYUNDAI", "SHARAYU HYUNDAI", "SHIRODE HYUNDAI", "SHIVAM HYUNDAI", "SHREEM HYUNDAI", "SHREENATH HYUNDAI", "SIDDH HYUNDAI LLP", "SOHAMM HYUNDAI", "SOMANI HYUNDAI", "STS HYUNDAI", "UJJWAL HYUNDAI", "UNIQUE HYUNDAI", "VISHAL HYUNDAI"],
    "Meghalaya": ["GOENKA HYUNDAI", "SHILONG HYUNDAI"],
    "Odisha": ["ADITYA HYUNDAI", "AKASHDEEP HYUNDAI", "BINOD HYUNDAI", "HSPL HYUNDAI", "INFINITY HYUNDAI", "KAVYA HYUNDAI", "KOSHALA HYUNDAI", "OSL HYUNDAI", "PREMIER HYUNDAI", "SAKAMBARI HYUNDAI", "UTKAL HYUNDAI"],
    "Punjab": ["BERKELEY HYUNDAI", "BRARS HYUNDAI", "DPG HYUNDAI", "GOYAL - HYUNDAI", "GOYAL HYUNDAI", "GROVER HYUNDAI", "JOSHI HYUNDAI", "KOSMO HYUNDAI", "MALWA HYUNDAI", "NOVELTY HYUNDAI", "PARK HYUNDAI", "PAUL HYUNDAI", "RAJA HYUNDAI", "YASHODHA HYUNDAI"],
    "Rajasthan": ["AJMER HYUNDAI", "BADOLA HYUNDAI", "BHARAT HYUNDAI", "CHANDRA HYUNDAI", "CHITTOR HYUNDAI", "DEORA HYUNDAI", "HINDUSTAN HYUNDAI", "JMV HYUNDAI", "KAMAL HYUNDAI", "KOTA HYUNDAI", "MARUDHARA HYUNDAI", "MODERN HYUNDAI", "MORANI HYUNDAI", "P L HYUNDAI", "PARAS HYUNDAI", "PL HYUNDAI", "PUNJAB HYUNDAI", "RAJA HYUNDAI", "ROSHAN HYUNDAI", "ROYALE HYUNDAI", "SANDEEP HYUNDAI", "SHIVAM HYUNDAI", "SHRI GANGA HYUNDAI", "SHRI SHAKUN HYUNDAI"],
    "Tamil Nadu": ["CHANDRA HYUNDAI", "DERIK HYUNDAI", "FPL HYUNDAI", "GOLDEN HYUNDAI SALEM", "GT HYUNDAI", "GT HYUNDAI DINDUGAL", "HIMAVARSINI HYUNDAI HOSUR", "KOVAI HYUNDAI", "KOVAI HYUNDAI HYUNDAI", "KUN HYUNDAI", "LAKSHMI HYUNDAI", "LOTUS HYUNDAI", "LOTUS HYUNDAI ERODE", "MOTOR PLAZA", "OXINA HYUNDAI", "PEEYESEM HYUNDAI KAMARAJ SALAI", "PEEYESEM HYUNDAI RAMNAD", "PEEYESEM HYUNDAI THOOTHUKUDI", "PEEYESYEM HYUNDAI", "SUSEE HYUNDAI BYPASS ROAD", "SUSEE HYUNDAI TIRUNELVELI", "V3 HYUNDAI", "VBSRS HYUNDAI", "VELLORE", "VETRI HYUNDAI"],
    "Telangana": ["BHARAT MOTOCORP PRIVATE LIMITED", "BHARATH HYUNDAI", "DWARAKA HYUNDAI", "FUSION HYUNDAI", "GEETHA HYUNDAI", "HEMA HYUNDAI", "HEMA MOTORS PVT LTD", "JSP HYUNDAI", "KUN HYUNDAI", "LAKSHMI HYUNDAI", "NEON HYUNDAI", "PRAKASH AUTOMOTIVES", "SANSAI HYUNDAI", "SASYA HYUNDAI", "TREND HYUNDAI"],
    "Tripura": ["JOYRAM AUTO", "NIMAI HYUNDAI", "PANNA MOTORS"],
    "Uttar Pradesh": ["ADITYA NARAIN HYUNDAI", "AKC HYUNDAI", "ARADHANA HYUNDAI", "ARJUN VASU HYUNDAI", "ARVIND HYUNDAI", "ARYAMAN HYUNDAI", "BALAJEE HYUNDAI", "BEEAAR HYUNDAI", "CAPITAL HYUNDAI", "CHAUDHARY HYUNDAI", "D S AUTOMOBILES", "DAS HYUNDAI", "DEV HYUNDAI", "DREAM HYUNDAI", "FORTUNE HYUNDAI", "G.P HYUNDAI", "GEETA HYUNDAI", "GP HYUNDAI", "HAPUR HYUNDAI", "JRD NIMBUS HYUNDAI", "JSV HYUNDAI", "KHANNA HYUNDAI", "KRISHNA HYUNDAI", "M R HYUNDAI", "M.R. HYUNDAI", "MB HYUNDAI", "NATRAJ HYUNDAI", "NIMBUS HYUNDAI", "NIRMAL HYUNDAI", "NRL HYUNDAI", "PAWAN HYUNDAI", "PREMIER HYUNDAI", "RAJENDRA HYUNDAI", "SACHIN HYUNDAI", "SAMUDRA HYUNDAI", "SANMATI HYUNDAI", "SAS HYUNDAI", "SHIEL HYUNDAI", "SHINE HYUNDAI", "SHIVA HYUNDAI", "SHIVANG HYUNDAI", "SHREE SANMATI HYUNDAI", "SONEBHADRA HYUNDAI", "TIRUPATI HYUNDAI", "VENKATESH HYUNDAI"],
    "Uttarakhand": ["BINDAL HYUNDAI", "BM HYUNDAI", "COMMERCIAL HYUNDAI", "DPM HYUNDAI", "SACHIN HYUNDAI", "UTTRAKHAND HYUNDAI"],
    "West Bengal": ["AMEET HYUNDAI", "BENGAL HYUNDAI", "BERLIA HYUNDAI", "DURGA HYUNDAI", "GAJRAJ HYUNDAI", "GIRIJA HYUNDAI", "KESHAV HYUNDAI", "KOUSHAL HYUNDAI", "MUKESH HYUNDAI", "RAJGARIHA HYUNDAI", "RUDRA HYUNDAI", "S N HYUNDAI", "SAINI HYUNDAI", "TOPLINK HYUNDAI"],
  },
  TATA: {
    "Andaman and Nicobar Islands": ["GENNEXT MOTORS(ANDAMANS) PVT LTD"],
    "Andhra Pradesh": ["HAROON CARS PVT LTD", "JASPER INDUSTRIES PVT LTD", "RITHVIKAA CARS PVT LTD", "SIVA SANKAR MOTORS PVT LTD", "TRISTAR AUTO AGENCIES VIZAG PVT LTD", "VARALAKSHMI AUTOMOBILES PVT LTD", "VENKATARAMANA MOTORS", "VIJAYABHARATHI AUTOMOBILES PVT LTD"],
    "Arunachal Pradesh": ["K SQUARE MOTORS PVT LTD"],
    "Assam": ["ASHUTOSH MOTORS AND ALLIED BUSINESS", "AXOM CARS LLP", "BHAGYASHREE MOTORS PVT LTD", "BPN CARS PVT LTD", "CHAMPAK AUTOMOBILES PVT LTD", "DHANSRI AUTO VENTURES PVT LTD", "HEMAVI MOTORS PVT LTD", "HIGHWAY WHEELS", "MARWET PETROLEUM AGENCY", "PRAGATI AUTOTECH PVT LTD", "PRAGATI TRADING COMPANY PVT LTD", "SUBHANGSHU MOTORS", "UTKARSH MOTOTECH PVT LTD"],
    "Bihar": ["ANANYA AUTO AGENCY PVT LTD", "GANGA VEHICLES PVT LTD", "GUINEA MOTORS PVT LTD", "IDEAL DEALERS PV PVT LTD", "KOSI AUTOTRACT PVT LTD", "KUSUMNATH AUTOMOBILES PVT LTD", "NITIRAJ MOTORS PVT LTD", "SHANKAR MOTORS PVT LTD", "SHRI SATYA SAI ROHTAS CAR DEALER PV", "SURVI CARS PVT LTD", "URMILA AUTOMOBILES PVT LTD", "YASHRAJ MOTORS PVT LTD"],
    "Chandigarh": ["JOSHI AUTOTECH PVT LTD", "KRISHNA ASSURED", "RSA DYNAMIC MOTORS LLP"],
    "Chhattisgarh": ["BHASIN VENTURES PVT LTD", "BIJJARGI MOTORS", "J D AUTONATION", "JAGDALPUR MOTORS (P) LTD", "MAHADEVA VEHICLES PVT LTD", "NATIONAL GARAGE (BRANCH OF", "SAIRAM AUTOMOBILES & SERVICES PVT L", "SHIVAM AUTOMOTIVE", "SHRI SALASAR AUTOMOTIVES PVT LTD", "SUNIL VEHICLES PVT LTD"],
    "Delhi": ["AUTOVIKAS SALES & SERVICE PVT LTD", "DELIGHT MOTORS PVT LTD", "DPS MOTOR CARS PVT LTD", "FRONTIER COMMERCIAL VEHICLES PVT LT", "GANGANAGAR AUTOMOBILES PVT LTD", "JASPER INDUSTRIES PVT LTD", "MALWA AUTOMOBILES PVT LTD", "SAB MOTORS PVT LTD", "SAGAR MOTORS", "SPARSH AUTOTECH PVT LTD", "TRUENORTH AUTOMOBILES PVT LTD", "ZEDEX MOBILITY LLP"],
    "Goa": ["DURGA MOTORS", "PRINCELY CARS PVT LTD"],
    "Gujarat": ["ABC AUTO LINK", "BHAGVATI AUTOLINK PVT LTD", "CARGO MOTORS AHMEDABAD PVT LTD", "FALCON MOTORS", "GAJANAND MOTORS PVT LTD", "GOKUL AUTO", "HARSOLIA BROTHERS", "INFINITY VEHICLES PVT LTD", "JAI GANESH AUTO HUB", "JAI GANESH AUTO ZONE", "PARIN MOTORS", "PARTH AUTO HUB PVT LTD", "PARTH AUTOCARS LLP", "PD CARS PVT LTD", "PRAGATI VEHICLES LLP", "PRAMUKH AUTOMOTIVE PVT LTD", "PROGRESSIVE CARS PVT LTD", "RIYA AUTOLINK", "SAIRAM CARS", "SHRADDHA MOTORS PVT LTD", "SHREEJI AUTOMART PVT LTD", "SP AUTOZONE", "SP CARS", "SP VEHICLES", "STELLAR AUTODRIVE PVT LTD", "SUPERNOVA MOTORS PVT LTD"],
    "Haryana": ["AARYAMAN AUTOMOBILES", "ANR AUTOMOBILES PVT LTD", "AUTOVIKAS SALES & SERVICE PVT LTD", "CSG AUTOMOBILES PVT LTD", "DHEERAJ MOTOCORP INDIA PVT LTD", "HIMGIRI AUTOMOBILES PVT LTD", "MAGAN WHEELS PVT LTD", "MAHADEV MOTORS", "METRO MOTORS", "METRO MOTORS PVT LTD", "MULTITECH MOTORS LLP", "PANCHKULA ROLLER FLOUR MILLS LTD", "PHYTRON MOBILITY PVT LTD", "PREMIUM MOTOCORP INDIA PVT LTD", "RAHUL AUTO ZONE LLP", "RAJ MOTORS", "RAMA AUTO CARS", "RP JHUNTHRA AUTOWHEELS PVT LTD", "SAHIB AUTOMOTIVE PVT LTD", "SISOTHYA E VENTURES PVT LTD", "SMPCD PVT LTD", "SWAN MOTORS PVT LTD", "TELMOS AUTOMOBILES PVT LTD", "ZEALTEL GLOBAL PVT LTD"],
    "Himachal Pradesh": ["J K R MOTORS PVT LTD", "J P MOTORS", "N G AUTOMOBILES PVT LTD"],
    "Jammu and Kashmir": ["FAIRDEAL AUTOMOTORS PVT LTD", "FAIRDEAL MOTORS & WORKSHOP PVT LTD", "HIMALAYAN AUTOMOBILES PVT LTD", "K Y AUTO PVT LTD", "SMAM AUTOMART PVT LTD"],
    "Jharkhand": ["ASL ENTERPRISES LTD", "ASL MOTORS", "BASUDEB AUTO LTD", "JAIMAA SHARDA AUTOMOBILES", "KRAFT AUTO PVT LTD", "RISING AUTO WHEELS PVT LTD", "SS MOTOGEN PVT LTD", "TIWARI AUTOMOBILES PVT LTD", "YAJNAND MOTORS LLP"],
    "Karnataka": ["ADISHAKTI CARS PVT LTD", "AUTO MATRIX", "BELLAD ENTERPRISES PVT LTD", "CAUVERY MOTORS PVT LTD", "KEY MOTOR VENTURES PVT LTD", "KHT AGENCIES PRIVATE LIMITED", "KHT AGENCIES PVT LTD", "KROPEX AUTO PVT LTD", "MANICKBAG AUTOMOBILES PVT LTD", "PRERANA MOTORS PVT LTD", "SREE AUTO", "URS KAR SERVICE CENTRE (P) LTD"],
    "Kerala": ["DERIK MOTORS PVT LTD", "HYSON MOTORS PVT LTD", "KVR AUTOMOTIVE PVT LTD", "KVR DREAM VEHICLES PVT LTD", "LUXON MOTORS PVT LTD", "MUTHOOT AUTOMOBILE SOLUTIONS PVT LT", "ROTANA MOTOR PVT LTD", "SREE GOKULAM MOTORS & SERVICES PVT", "SREE GOKULAM MOTORS AND SERVICES PV", "TRIVANDRUM MOTORS PVT LTD"],
    "Ladakh": ["LADAKH SINDH MOTORS"],
    "Madhya Pradesh": ["ANAND MOTOREN PVT LTD", "COMMERCIAL AUTOMOBILES CAR PVT LTD", "FRONTIER MOTOCORP", "FRONTLEAF MOTORS PVT LTD", "JAGDISH AUTOMOTIVE PVT LTD", "PRAHLAD ABHIKARAN (CAR DIVISION)", "R R AUTOMOBILES", "SAMARTH CARS PVT LTD", "SANGHI BROTHERS ( INDORE ) PVT LTD", "SETH AND SONS", "SHYAM AUTOMOTIVE", "SUGANDH AUTOMOBILES", "SUGANDH AUTOMOTIVE", "SUNIL AUTOMOTIVES", "VARENYAM MOTOR CAR", "VELOCITY AUTOMOBILES PVT LTD"],
    "Maharashtra": ["ADITYA AUTOCARE PVT LTD", "AGATE AUTOMOTIVE PVT LTD", "AILSINGHANI CARS PVT LTD", "DEVAKI MOTORS LLP", "FORTUNE CARS PVT LTD", "GARVE CARS PVT LTD", "GOVIND CARS", "HERITAGE MOTORS (MUMBAI) PVT LTD", "INDERJIT CARS PVT LTD", "J V MOTORS", "JAIKA MOTORS PVT LTD", "JAY AUTOMOTIVE", "KAMU MOTORS", "KESHVA MOTORS", "MAC VEHICLES PVT LTD", "MAKS ECO MOTORS PVT LTD", "MP AUTOMOTORS PVT LTD", "MUTHA MOTORS", "PADMAJA MOTORS", "PANCHJANYA AUTOMOBILE", "PUNEET CARS PVT LTD", "RUDRA MOTORS", "SAI BABA AUTOWHEELS PVT LTD", "SANYA MOTORS PVT LTD", "SATISH MOTORS PVT LTD", "SP AUTOHUB", "SRIDHA MOTORS PVT LTD", "STERLING MOTORS", "SUDARSHAN MOTORS", "SURYODAY AUTO PVT LTD", "TATA PASSENGER ELECTRIC MOBILITY LT", "UJWAL AUTOMOTIVES PVT LTD", "UNITY MOTORS PVT LTD", "WELLWISHER CARS PVT LTD"],
    "Manipur": ["TIDDIM MOTORS"],
    "Meghalaya": ["FRANK MOTORS"],
    "Mizoram": ["NATIONAL BUSINESS ENTERPRISES"],
    "Nagaland": ["NILI MOTORS"],
    "Odisha": ["DION AUTOMOTIVES PVT LTD", "GRAMPS AUTOTEC PVT LTD", "GUGNANI AUTOCARS PVT LTD", "LANKESWARI MOTORS PVT LTD", "MONALISHA MOTORS PRIVATE LIMITED", "SHREEKHETRA AUTOMOTIVES PVT LTD", "SS STEELLOY PVT LTD", "TRUPTI ENTERPRISES PVT LTD"],
    "Puducherry": ["SCHAKRALAYA MOTORS PVT LTD"],
    "Punjab": ["A G MOTORS", "DADA MOTORS PVT LTD", "DEV BHOOMI AUTO CARS LLP", "ES EM AUTOMOBILES PVT LTD", "GANPATI SIGNATURE CARS PVT LTD", "KOSMO VEHICLES PVT LTD", "RAHUL PAM PVT LTD", "SAHIB AUTOMOTIVE PVT LTD", "SIDHAM MOTORS PVT LTD"],
    "Rajasthan": ["AKAR FOURWHEEL PVT LTD", "AUTOPLEX AV", "BRIJWHEEL AUTOMOBILES PVT LTD", "CHAMBAL MOTOCORP LLP", "CHAMBAL MOTORS PVT LTD", "CLASSIC MOTORS", "DAKSH AUTOMOTIVE PVT LTD", "DHOOT AUTO PVT LTD", "DUNAC AUTOMOBILES PVT LTD", "FIRST MOBITAL PVT LTD", "KAMAL PASSENGER VEHICLE PVT LTD", "MARUDHARA MOTORS", "MUDGAL MOTORS", "PRATAP NEXGEN CARS PVT LTD", "ROSHAN MOTORS (CARS) PVT LTD", "SHREE CHARBHUJA AUTOMOBILES", "SHREE SHYAM MOTORS", "SHRI KRISHNA FOUR WHEELS PVT LTD", "SHRIKRISHNA RAJ FOURWHEELS PVT LTD", "SP AUTOMOTIVE", "YASH MOTORS"],
    "Sikkim": ["RANGEET AUTO PVT LTD"],
    "Tamil Nadu": ["DERIK MOTORS PVT LTD", "FPL EAUTO PRIVATE LTD", "FPL EAUTO PVT LTD", "GURUDEV MOTORS CHENNAI LLP", "JAYARAJ KARZ", "KAVERI GARAGE PVT LTD", "KUN CARS PRIVATE LIMITED", "KUN CARS PVT LTD", "SAYAR AAUTOMOTIVE PVT LTD", "SCHAKRALAYA MOTORS PVT LTD", "SGA MOTORS INDIA PVT LTD", "SREE GOKULAM MOTORS & SERVICES PVT", "SRI CHIMA CARS PVT LTD", "SRILAKSHMI AUTO ENTERPRISES INDIA", "TAFE ACCESS LIMITED", "THE TRUE SAI WORKS", "V S VICTORY CARZ PVT LTD"],
    "Telangana": ["JASPER INDUSTRIES PVT LTD", "MALIK AUTOWORLD PVT LTD", "ORANGE AUTO PVT LTD", "PRATHAMMALIK AUTO MATRIX PVT LTD", "SELECT CARS", "SELECT MOTORS", "SREE VENKATESWARA MOTORS (INDIA)", "TEJASWI AUTOMOBILES", "VENKATARAMANA MOTORS", "VVC AUTO WORLD"],
    "Tripura": ["PROGRESSIVE AUTOMOBILES PVT LTD"],
    "Uttar Pradesh": ["ANJNEY AUTOMOBILES PVT LTD", "ASHOK AUTO SALES LTD", "BR AUTOVENTURES PVT LTD", "BRIJLAX MOTORS PVT LTD", "BRINDAVAN SHELTERS PVT LTD", "G P MOTORS PVT LTD", "GOLA GANPATI MOTORS", "GOLDRUSH SALES & SERVICES LTD", "GROVER TRADE LINKS PVT LTD", "ICON CARS KANPUR PVT LTD", "JMK MOTORS PVT LTD", "KD MOTOCORP INDIA PVT LTD", "MAA SATYAVATI MOTORS PVT LTD", "MAGAN MOTORS PVT LTD", "MANGALAM AUTOWORLD PVT LTD", "MASCOT MOTORS PVT LTD", "MIDAS MOTORS", "NAWAL MOTORS", "OKEY MOTORS PVT LTD", "PUNEET AUTO SALES PVT LTD", "R A MOTORS PVT LTD", "R K LAXMI GENERAL SALES LTD", "R K LAXMI GENERAL SALES PVT LTD", "RAJINDRA MOTOR COMPANY PVT LTD", "RANA MOTORS", "SAB MOTORS PVT LTD", "SAGAR MOTORS", "SEVEN AUTOCORP PVT LTD", "SHREE BALAJI AUTOWHEELS (INDIA) PVT", "SHREE DEV WHEELS PVT LTD", "SHREE VASU AUTOMOBILES PVT LTD", "SHREE VASU AUTOWORLD LLP", "SOCIETY MOTORS LTD", "SRM MOTORS PVT LTD", "SUPERB AUTOCORP PVT LTD", "TRIDENT VEHICLES PVT LTD", "VEDANT BALAJI AUTOMOVERS PVT LTD"],
    "Uttarakhand": ["AMIT AUTOCARS PVT LTD", "MANGALAM AUTOWORLD PVT LTD", "MIDAS MOTORS", "OBERAI MOTORS", "TRUECONNECTING WHEELS PVT LTD"],
    "West Bengal": ["BANERJEE AUTOMOBILES PVT LTD", "CHANDRANI ENTERPRISES PVT LTD", "DULICHAND MOTORS PVT LTD", "K B MOTORS PVT LTD", "KRISHNAA CAR WORLD PVT LTD", "LEXUS MOTORS LTD", "NIBIR MOTORS PVT LTD", "OSL FUTURE PVT LTD", "PRAADIP MOTORS LLP", "RANGEET AUTO PVT LTD", "RANGEVIEW AUTO PVT LTD", "RELIANCE INDUSTRIAL CONSORTIUM LTD", "T C MOTORS PVT LTD"],
  },
  MAHINDRA: {
    "Andaman and Nicobar Islands": ["Jadwet Trading Company"],
    "Andhra Pradesh": ["AUTOMOTIVE MANUFACTURERS PVT LTD", "BALAJI AGENCIES & INDUSTRIES", "M & N Motors Pvt. Ltd.", "M.G.B.Mobiles", "Motorline Auto Pvt. Ltd.", "Neon Motors Pvt Ltd"],
    "Arunachal Pradesh": ["ICONIC AUTOMOBILES"],
    "Assam": ["ASSAM MOTORS", "BISWANATH ASHOK AUTO LLP", "G. D. MOTORS", "HATORKI MOTORS PRIVATE LIMITED", "Industrial & Farm Equipme", "MAHABHAIRAV AUTO LLP", "Poddar Autocorp Pvt. Ltd.", "R. D Automobiles", "Ramnarayan Shivprasad", "SABITA AUTOMOBILES"],
    "Bihar": ["Amit Automobiles", "APR Automobiles Pvt. Ltd.", "BRAJESH AUTOMOBILES PVT LTD", "CHANDAMAMA MOTORS", "KIRAN AUTOMOBILES PVT LTD", "LEADER AUTOMOBILES", "NEXGEN SOLUTION TECHNOLOGIES", "RADHA HARI MOTORS", "ROHIT AUTOMOBILES", "SHIV SHAKTI WAHAN PVT LTD", "SHREE R C ENTERPRISES", "SIWAN TRACTORS PVT LTD", "SIWAN TRACTORS PVT LTD.", "SUN SHINE AUTOS PVT LTD"],
    "Chandigarh": ["HARBIR AUTOMOBILE - Chandigarh"],
    "Chhattisgarh": ["AUTO CENTRE", "MODEL FUELS PVT LTD", "RALAS AUTOMOBILES", "RALAS MOTORS", "Shivnath Automobiles Pvt. Ltd.", "SHIVNATH MOTORS (I) PVT. LTD.", "Star Automobiles - Ambikapur"],
    "Delhi": ["HARBANS MOTORS PVT LTD", "INDRAPRASTHA AUTOMOBILES PVT LTD", "KONCEPT AUTOMOBILES PVT LTD", "SHIVA AUTOCAR (INDIA) PVT. LTD", "Sri Durga Automobiles", "SYNERGY CARS (KONCEPT AUTOMOBILES PVT. LTD.)", "UNITED AUTOMOBILES", "VS ECO POWER PVT LTD (Shubum Sai)"],
    "Goa": ["NAIK MOTORS"],
    "Gujarat": ["AMBER AUTO", "AMBER AUTOMOBILES", "ATUL AUTOMOTIVES", "B. Mangatram & Co.", "BHURAWALA MOTORS", "Caravel Motors Pvt. Ltd.", "GALLOPS MOTORS PVT LTD", "M.M.VORA AUTOMOBILES PVT LTD", "MARSHAL TRADING COMPANY Grp", "Mega Automobiles Pvt. Ltd", "NANAVATI AUTOMOTIVE", "Param Automobiles Pvt. Ltd.", "PRESIDENT MOTORS", "Punjab Automobiles (India", "SAMRAT CARS PVT LTD", "Shital Motors Ltd.", "SHIVAM SALES CORPORATION", "SHRIJEE MOTORS", "SIDDHIVINAYAK MOTORS PVT LTD"],
    "Haryana": ["DEWAN FOURWHEELS PVT. LTD.", "GARG MOTORS", "Harbir Automobile Pvt. Ltd. - Panchkula", "Kbs Motors Pvt. Ltd.", "Koncept - Group Gurgaon", "LEKH RAJ AUTO PLAZA PVT LTD", "LOHCHAB MOTOR COMPANY PVT LTD", "P. P. AUTOMOTIVE PVT LTD", "P.P. AUTOMOTIVE PVT. LTD.", "PP SYSTEMS AND SERVICES", "Prime Automobiles Pvt. Ltd.", "SUPREME MOBILES PVT LTD", "TROB AUTO INDIA PVT. LTD.", "United Automobiles Group Delhi"],
    "Himachal Pradesh": ["J S Grover Autos Pvt Ltd", "Simla Automobiles Pvt. Ltd.", "Simla Automobiles Pvt.Ltd", "SNOWVIEW AUTOMOBILES PVT LTD"],
    "Jammu and Kashmir": ["ASTRO INDIA AUTOMOBILE PVT LTD", "HIMALAYAN MOTORS"],
    "Jharkhand": ["ANAND MOTORS", "BALAJI AUTO WORKS PVT. LTD.", "MODEL FUELS PVT LTD", "NEXGEN SOLUTION TECHNOLOGIES", "NEXGEN SOLUTION TECHNOLOGIES PVT LTD", "PRATIK AUTOMOBILES", "TEKRIWAL MOTORS PVT LTD", "TITANIA MOTOCORP PVT LTD", "UTKAL AUTO COACH PVT LTD"],
    "Karnataka": ["Anantcars Auto Pvt. Ltd.", "AUTOMOTIVE MANUFACTURERS PVT LTD(PPS MOTORS)", "Bellary Motor Sales Pvt.L", "H D Motors", "INDIA GARAGE", "KARNATAKA AGENCIES", "MAHANTH MOTORS", "SANTOSH AUTO WINGS", "SHAH MOTORS", "SIREESH AUTO PVT LTD", "SUTARIA AUTO CENTER"],
    "Kerala": ["CHERUKARA VEHICLES PVT. LTD.(CBC Motors)", "ERAM MOTORS PVT. LTD.", "HORIZON MOTORS INDIA PVT. LTD.", "INTREPID WORKS PVT. LTD.", "POTHEN AUTOS PVT. LTD.", "PPS MOTORS PVT. LTD.(AUTOMOTIVE MANUFACTURERS PVT.LTD)", "SLEEBA AND SONS AUTOMOTIVE", "VAYALAT AUTOMOBILES PVT LTD", "VEER"],
    "Ladakh": ["MENTOKLING MOTORS", "VEHICLEAGE KARGIL"],
    "Madhya Pradesh": ["ACCORD MOTORS", "Amber Automotives", "BHAGAWATI FRONTLINE MOTORIZER", "BHAGAWATI INDIA MOTORIZER", "BHAGIRATH MOTORS INDIA PVT LTD", "Bhagwati Elite Motors", "Bhagwati Elite Motors Pvt Ltd.", "BUNDELKHAND AUTOMOBILES PVT LT", "C. I. Automotors Pvt. Ltd.", "RATHI MOTORS (SHUJALPUR) PVT LTD", "Rishab Motor Sales Pvt.Lt", "Royal Automobiles Ltd.", "SHRI KAKAJI AUTOMOTIVES", "SOMYA VEHICLES PVT LTD", "STAR AUTOMOBILES", "STAR AUTOMOBILES (M.P.) Ltd", "Win Win Automobiles Pvt.Group"],
    "Maharashtra": ["AAKASH AUTOMOTIVES", "BHARANE MOTORS", "Bhavin Wheels Pvt. Ltd.", "BHAVNA AUTOMOBILES PVT LTD", "CORNERSTONE AUTOMOBILES", "Gadre Autocon Pvt. Ltd.", "GANDHI MOTORS", "Hare Krishna", "Indomobil Sales And Servi", "JAY MOTORS", "JITENDRA MOTORS PVT LTD", "NAIK MOTORS", "NANAVATI AUTOMOTIVE", "NBS INTERNATIONAL LTD", "PROVINCIAL AUTOMOBILE COMPANY", "Randhawa Motors", "Ratnaprabha Motors", "SABLOK CARS", "SAHYADRI MOTORS PVT LTD", "SAHYADRI MOTORS PVT.LTD", "SALASAR AUTOCRAFTS PVT. LTD.", "SATPUDA AUTOMOBILES", "SAVAN IB AUTOWINGS PVT. LTD.", "Silver Jubilee Motors Ltd", "TRENDY WHEELS PVT LTD", "Ujwal Enterprises (I) Pvt", "UNNATI MOTORS", "UNNATI MOTORS (DIV OF MICROPARK LOGSITICS PVT. LTD.)"],
    "Manipur": ["SHIVZ AUTOTECH PVT LTD"],
    "Meghalaya": ["SL ROKLAND MOTORE LLP"],
    "Mizoram": ["MANA MOTORS"],
    "Nagaland": ["Apex Motor Enterprises"],
    "Odisha": ["ADITYA MOTORS", "BASANTI AUTO AGENCY", "G N AUTONATION", "KRISHNA AUTOMOTIVE", "MINERVA AUTOMOBILES PVT LTD", "Paramount Automotives Pvt Ltd", "Siddhi Laxmi Motors", "Utkal Automobiles Ltd."],
    "Punjab": ["AVC MOTORS", "BRAR AUTO WHEELS", "Dada Motors", "J S GROVER AUTOMOTIVES", "MAKKAR MOTORS PVT LTD", "Makkar Motors Pvt. Ltd.", "NOVELTY WHEELS PVT. LTD.", "Punj Auto Pvt Ltd", "RAGA MOTORS PVT LTD", "RAJ MOTORS", "RAJ VEHICLES MOHALI", "Raj Vehicles Patiala", "RAJ VEHICLES PVT LTD", "WORLDWIDE AUTOZONE PVT. LTD."],
    "Rajasthan": ["Auto World Group", "Bhilwara Agro Auto Service group", "BIKANER MOTORS PRIVATE LIMITED", "Bikaner Motors Pvt.Limite", "Evegreen Group", "GEHLOT MOTORS PVT LTD", "J.S.FOURWHEEL MOTORS PVT LTD", "K. S. AUTOMOBILES PVT LTD", "K. S. Automobiles Pvt. Ltd.", "K. S. Motors Pvt. Ltd.", "NAGAUR AUTOMOBILES PVT LTD", "O S Motors Ltd.", "PARAM AUTOMOBILES PVT LTD", "V.D.Motors Pvt.Ltd."],
    "Sikkim": ["RAJSONS ENTERPRISES"],
    "Tamil Nadu": ["AUTOMOTIVE MANUFACTURERS PVT LTD", "CAI AUTO INDUSTRIES PVT LTD", "DERIK MOTORS (P) LTD", "Jain Cars And Auto Sales", "MARUDHAR MISHRI MOTORS LLP"],
    "Telangana": ["AUTOMOTIVE MANUFACTURERS PVT LTD", "Motorline Auto Pvt. Ltd.", "Neon Motors Pvt Ltd"],
    "Tripura": ["TARASANKAR MOTOR PVT LTD"],
    "Uttar Pradesh": ["A 2 Z Auto Wheels Pvt. Ltd.", "A AUTOMOVERS PVT LTD", "ABHINANDAN AUTOZONE", "AGARWAL AUTO SALES", "AMIT MOTORS PVT LTD", "ATMARAM AUTO ENTERPRISES", "Brijraj Motors Pvt. Ltd.", "DEEP AUTOMOBILES", "DHRUV TARA AUTOMOTIVES PVT LTD", "Dua Cars & Motors (India) Pvt. Ltd.", "Hora Motors Pvt. Ltd.", "Jai Kumar Arun Kumar Pvt.", "KALYAN SALES LLP", "Kamlesh Autowheels Pvt. Ltd.", "KAMLESH AUTOWHEELS PVT. LTD.", "Mahalaxmi Motors", "Meet Associates Pvt. Ltd.", "MOSARAM ENTERPRISES LIMITED", "NARAIN AUTOMOBILES", "Nataraj Automobiles", "Om Auto Pvt. Ltd.", "OM AUTOMOBILES PVT LTD.", "RAJ INDIA AUTO PVT LTD", "RAJENDRA AUTO WHEELS PVT LTD", "Sardar Motors(Autowheel)P", "SHIVA AUTOCAR (INDIA) PVT. LTD", "SHIVA AUTOCAR (INDIA) PVT. LTD.", "SHIVA AUTOMOBILES PVT LTD", "SHREE SHYAM JI AUTOMOTIVE LLP", "SHREE TIRUPATI AUTO", "STAR MOTORS", "TIRUPATI VEHICLES PVT. LTD.", "UNITED AUTOMOBILES", "V C MOTORS PVT LTD", "Vineet Automobiles Pvt. Ltd."],
    "Uttarakhand": ["BAJRANG MOTORS", "Dehradun Premier Motors", "KUMAR AUTOWHEELS PVT. LTD.", "MIGHTY AUTO WHEELS PVT LTD"],
    "West Bengal": ["Khokan Motor Works Group", "M.S. Motors", "NARBHERAM LEASING CO PVT LTD", "ROYAL MOTORS", "RUDRA AUTOMART PVT LTD", "S N MOTORS PVT LTD", "Saluja Auto Retails Pvt. Ltd.", "SHREE AUTOMOTIVE PVT LTD", "SONA WHEELS PRIVATE LIMITED", "STAR INDIA AGENCIES PVT LTD", "SUPREME ELECTROTECH PVT LTD"],
  },
};

/** Fallback so the State field still works if the geo API is unreachable. */
const INDIAN_STATES_FALLBACK = [
  "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam",
  "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli", "Daman and Diu",
  "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir",
  "Jharkhand", "Karnataka", "Kerala", "Ladakh", "Lakshadweep", "Madhya Pradesh",
  "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha",
  "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
  "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
];

// ─── Form shape ──────────────────────────────────────────────────────────────
interface FormState {
  email: string;
  salesperson: string;
  oem: string;
  contact_mode: string;
  visit_date: string;
  state: string;
  city: string;
  dealership: string;
  address: string;
  contact_person: string;
  contact_number: string;
  designation: string;
  car_sales: string;
  seat_cover_sales: string;
  mats_sales: string;
  channel: string; // MSIL only — Arena / Nexa
}

/** Local calendar date as YYYY-MM-DD. toISOString() would shift to UTC and can
 *  land on the previous day for IST users late in the evening. */
const todayISO = () => {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

/** "22 Jul 2026" — friendlier than the raw ISO value in a read-only field. */
const formatDisplayDate = (iso: string) => {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d).toLocaleDateString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
  });
};

const EMPTY: FormState = {
  email: "",
  salesperson: "",
  oem: "",
  contact_mode: "",
  visit_date: todayISO(),
  state: "",
  city: "",
  dealership: "",
  address: "",
  contact_person: "",
  contact_number: "",
  designation: "",
  car_sales: "",
  seat_cover_sales: "",
  mats_sales: "",
  channel: "",
};

const FIELD_LABELS: Record<keyof FormState, string> = {
  email: "Email",
  salesperson: "Sales Person's Name",
  oem: "OEM",
  contact_mode: "Visit / Calling",
  visit_date: "Visit / Calling Date",
  state: "State",
  city: "City",
  dealership: "Dealership",
  address: "Address",
  contact_person: "Contact Person",
  contact_number: "Contact Number",
  designation: "Designation",
  car_sales: "Monthly Car Sales",
  seat_cover_sales: "Monthly Seat Cover Sales",
  mats_sales: "Monthly Mats Sales",
  channel: "Arena / Nexa",
};

// Every always-visible field is required. Derived/auto fields (email, visit_date)
// and conditional ones (channel — MSIL only; mats_sales — all but MSIL; photo —
// Visit only) are
// validated separately in handleSubmit so they aren't demanded when hidden.
const REQUIRED: (keyof FormState)[] = [
  "salesperson",
  "oem",
  "contact_mode",
  "visit_date",
  "state",
  "dealership",
  "city",
  "address",
  "contact_person",
  "contact_number",
  "designation",
  "car_sales",
  "seat_cover_sales",
];

// ─── Field styling ───────────────────────────────────────────────────────────
// h-[52px] + text-base (16px) — below 16px iOS Safari zooms the viewport on focus.
const fieldBase =
  "w-full h-[52px] px-4 rounded-2xl text-base text-gray-900 bg-white outline-none transition-colors duration-200 border border-gray-200 focus:border-orange-400 focus:ring-4 focus:ring-orange-100";
const areaBase =
  "w-full px-4 py-3 rounded-2xl text-base text-gray-900 bg-white outline-none transition-colors duration-200 border border-gray-200 focus:border-orange-400 focus:ring-4 focus:ring-orange-100 resize-y";

function Label({ children, required }: { children: React.ReactNode; required?: boolean }) {
  return (
    <label className="text-xs font-bold uppercase tracking-wider text-gray-500">
      {children}
      {required && <span className="text-orange-500 ml-0.5">*</span>}
    </label>
  );
}

function Section({
  title, icon, children,
}: { title: string; icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center gap-2">
        <span className="text-orange-500">{icon}</span>
        <h2 className="text-[11px] font-bold uppercase tracking-[0.18em] text-gray-700">{title}</h2>
        <div className="flex-1 h-px bg-gray-100" />
      </div>
      {children}
    </div>
  );
}

/** Custom dropdown — a native <select> renders an unstyleable OS menu (blue
 *  highlight, system font), so the list is built by hand to match the form. */
function SelectField({
  label, required, options, value, onChange, disabled, hint, placeholder,
}: {
  label: string; required?: boolean; options: string[]; value: string;
  onChange: (v: string) => void; disabled?: boolean; hint?: string;
  placeholder?: string;
}) {
  const [open, setOpen] = useState(false);
  const boxRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onDocClick = (e: MouseEvent) => {
      if (boxRef.current && !boxRef.current.contains(e.target as Node)) setOpen(false);
    };
    const onEsc = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); };
    document.addEventListener("mousedown", onDocClick);
    document.addEventListener("keydown", onEsc);
    return () => {
      document.removeEventListener("mousedown", onDocClick);
      document.removeEventListener("keydown", onEsc);
    };
  }, [open]);

  return (
    <div className="flex flex-col gap-2" ref={boxRef}>
      <Label required={required}>{label}</Label>
      <div className="relative">
        <button
          type="button"
          disabled={disabled}
          onClick={() => setOpen((o) => !o)}
          className={`${fieldBase} flex items-center justify-between text-left ${
            disabled ? "bg-gray-50 cursor-not-allowed" : ""
          } ${open ? "border-orange-400 ring-4 ring-orange-100" : ""}`}
        >
          <span className={value ? "text-gray-900" : "text-gray-400"}>
            {value || (disabled ? hint ?? "Select…" : placeholder ?? "Select…")}
          </span>
          <motion.span
            animate={{ rotate: open ? 180 : 0 }}
            transition={{ duration: 0.18 }}
            className="text-gray-400 shrink-0"
          >
            <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
              <path d="M2.5 4.5L6 8l3.5-3.5" stroke="currentColor" strokeWidth="1.6"
                strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </motion.span>
        </button>

        <AnimatePresence>
          {open && !disabled && (
            <motion.div
              initial={{ opacity: 0, y: -6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.15 }}
              className="absolute z-30 left-0 right-0 top-[58px] max-h-64 overflow-y-auto rounded-2xl border border-gray-200 bg-white p-1.5"
              style={{ boxShadow: "0 12px 32px rgba(0,0,0,0.12)" }}
            >
              {options.map((o) => {
                const active = o === value;
                return (
                  <button
                    key={o}
                    type="button"
                    onClick={() => { onChange(o); setOpen(false); }}
                    className={`w-full text-left px-3.5 py-3 rounded-xl text-base transition-colors flex items-center justify-between gap-2 ${
                      active
                        ? "bg-orange-50 text-orange-700 font-semibold"
                        : "text-gray-700 hover:bg-gray-50 active:bg-orange-50"
                    }`}
                  >
                    <span>{o}</span>
                    {active && <Check size={16} className="shrink-0 text-orange-500" />}
                  </button>
                );
              })}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

/** Type-to-filter combobox. Falls back to plain free text when no options exist. */
function SearchableField({
  label, required, options, value, onChange, placeholder, disabled, hint, loading,
}: {
  label: string; required?: boolean; options: string[]; value: string;
  onChange: (v: string) => void; placeholder?: string; disabled?: boolean;
  hint?: string; loading?: boolean;
}) {
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const boxRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const onDocClick = (e: MouseEvent) => {
      if (boxRef.current && !boxRef.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", onDocClick);
    return () => document.removeEventListener("mousedown", onDocClick);
  }, []);

  // Show the committed value until the user starts typing a new search.
  const shown = open ? query : value;
  const matches = useMemo(() => {
    const q = query.trim().toLowerCase();
    const list = q ? options.filter((o) => o.toLowerCase().includes(q)) : options;
    return list.slice(0, 50);
  }, [options, query]);

  return (
    <div className="flex flex-col gap-2" ref={boxRef}>
      <Label required={required}>{label}</Label>
      <div className="relative">
        <Search
          size={15}
          className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"
        />
        <input
          className={`${fieldBase} pl-10 ${disabled ? "bg-gray-50" : ""}`}
          value={shown}
          disabled={disabled}
          placeholder={disabled ? hint ?? placeholder : loading ? "Loading…" : placeholder}
          autoComplete="off"
          onFocus={() => { setOpen(true); setQuery(""); }}
          onChange={(e) => {
            setQuery(e.target.value);
            setOpen(true);
            // Free-text is allowed — keep the typed value even with no match.
            onChange(e.target.value);
          }}
        />
        {value && !disabled && (
          <button
            type="button"
            onClick={() => { onChange(""); setQuery(""); }}
            className="absolute right-3 top-1/2 -translate-y-1/2 h-7 w-7 rounded-full flex items-center justify-center text-gray-400 active:bg-gray-100"
            aria-label={`Clear ${label}`}
          >
            <X size={14} />
          </button>
        )}
        <AnimatePresence>
          {open && !disabled && matches.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: -6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.15 }}
              className="absolute z-30 left-0 right-0 top-[58px] max-h-64 overflow-y-auto rounded-2xl border border-gray-200 bg-white p-1.5"
              style={{ boxShadow: "0 12px 32px rgba(0,0,0,0.12)" }}
            >
              {matches.map((o) => {
                const active = o === value;
                return (
                  <button
                    key={o}
                    type="button"
                    onClick={() => { onChange(o); setQuery(""); setOpen(false); }}
                    className={`w-full text-left px-3.5 py-3 rounded-xl text-base transition-colors flex items-center justify-between gap-2 ${
                      active
                        ? "bg-orange-50 text-orange-700 font-semibold"
                        : "text-gray-700 hover:bg-gray-50 active:bg-orange-50"
                    }`}
                  >
                    <span>{o}</span>
                    {active && <Check size={16} className="shrink-0 text-orange-500" />}
                  </button>
                );
              })}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

// ─── City, taken from the dealership ────────────────────────────────────────
// Shown instead of the city picker once the chosen dealer knows where it is.
// It is deliberately not editable: the whole point of the dealer list carrying
// a city is that every visit to one outlet lands on the same city string, so
// the visit can be counted against that outlet.
function DerivedCity({ city }: { city: string }) {
  return (
    <div className="flex flex-col gap-2">
      <Label required>{FIELD_LABELS.city}</Label>
      <div className={`${fieldBase} flex items-center justify-between bg-gray-50 text-gray-700`}>
        <span>{city}</span>
        <MapPin size={15} className="text-gray-400 shrink-0" />
      </div>
      <p className="text-xs text-gray-400">From the selected dealership.</p>
    </div>
  );
}

// ─── Add new dealership ────────────────────────────────────────────────────
// Inline panel opened from the dealership field when the one a rep needs isn't
// in the list. Saves straight to the DB master list (see routers/visit_log.py
// POST /visit-log/dealerships) and never touches the log-book sheet — that is
// only written on final form submit.
//
// City IS asked for here, unlike before. A dealer added without one can never
// be told apart from another outlet of the same group, which is exactly the
// ambiguity this list exists to remove.
function AddDealerPanel({
  oem, state, cities, citiesLoading, onAdd, onClose,
}: {
  oem: string; state: string; cities: string[]; citiesLoading?: boolean;
  onAdd: (name: string, city: string) => Promise<void>; onClose: () => void;
}) {
  const [name, setName] = useState("");
  const [city, setCity] = useState("");
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState("");

  const submit = async () => {
    if (!name.trim()) { setErr("Enter the dealership name."); return; }
    if (!city.trim()) { setErr("Pick the city this dealership is in."); return; }
    setSaving(true);
    setErr("");
    try {
      await onAdd(name.trim(), city.trim());
      onClose();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Could not add dealership.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: -6 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -6 }}
      transition={{ duration: 0.15 }}
      className="mt-2 rounded-2xl border border-orange-200 bg-orange-50/60 p-4 flex flex-col gap-3"
    >
      <div className="flex items-center justify-between">
        <span className="text-xs font-bold uppercase tracking-wider text-orange-700">
          New dealership · {oem} · {state}
        </span>
        <button type="button" onClick={onClose} aria-label="Cancel" className="text-gray-400 active:text-gray-600">
          <X size={16} />
        </button>
      </div>
      <div className="flex flex-col gap-2">
        <Label required>Dealership name</Label>
        <input
          className={fieldBase}
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Enter dealership name"
          autoFocus
        />
      </div>
      <SearchableField
        label={FIELD_LABELS.city}
        required
        options={cities}
        value={city}
        onChange={setCity}
        placeholder="Search city…"
        loading={citiesLoading}
      />
      {err && <p className="text-sm text-red-600">{err}</p>}
      <button
        type="button"
        onClick={submit}
        disabled={saving}
        className="h-11 rounded-xl bg-orange-500 text-white font-semibold flex items-center justify-center gap-2 active:bg-orange-600 disabled:opacity-60"
      >
        {saving ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
        {saving ? "Saving…" : "Save & use this dealership"}
      </button>
    </motion.div>
  );
}

// ─── Splash ──────────────────────────────────────────────────────────────────
function Splash() {
  return (
    <motion.div
      key="splash"
      initial={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.45 }}
      className="fixed inset-0 z-50 flex flex-col items-center justify-center px-6"
      style={{ background: "linear-gradient(150deg, #1a1005 0%, #2b1608 55%, #3a1a08 100%)" }}
    >
      <motion.img
        src={logoSrc}
        alt="Amato Automotive"
        className="h-14 w-auto"
        style={{ filter: "brightness(0) invert(1)" }}
        initial={{ opacity: 0, y: 12, scale: 0.96 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ duration: 0.7, ease: [0.4, 0, 0.2, 1] }}
      />
      <motion.p
        className="text-[10px] font-bold uppercase tracking-[0.28em] text-white/70 mt-4 text-center"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.35, duration: 0.5 }}
      >
        OE Network · Visit Log
      </motion.p>
      <motion.div
        className="mt-8 h-0.5 rounded-full bg-orange-500/80"
        initial={{ width: 0 }}
        animate={{ width: 110 }}
        transition={{ delay: 0.2, duration: 1.1, ease: "easeInOut" }}
      />
    </motion.div>
  );
}

export default function VisitLogFormPage() {
  const [showSplash, setShowSplash] = useState(true);
  const [form, setForm] = useState<FormState>(EMPTY);

  // Remark categories → note text. A category is "selected" when it has a key.
  const [remarks, setRemarks] = useState<Record<string, string>>({});

  const [photo, setPhoto] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");

  const [states, setStates] = useState<string[]>(INDIAN_STATES_FALLBACK);
  const [cities, setCities] = useState<string[]>([]);
  const [citiesLoading, setCitiesLoading] = useState(false);

  // The dealer master list now lives in the DB so reps can extend it from here.
  // DEALERSHIPS_BY_OEM_STATE stays as the offline fallback: if the API is down,
  // the form still works with the list as it stood at build time.
  const [dealers, setDealers] =
    useState<Record<string, Record<string, (string | DealerOption)[]>>>(DEALERSHIPS_BY_OEM_STATE);
  const [addingDealer, setAddingDealer] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setShowSplash(false), 1600);
    return () => clearTimeout(t);
  }, []);

  // Dealer master list from the DB; the hardcoded constant stays as the fallback.
  useEffect(() => {
    let alive = true;
    fetch(`${API_URL}/visit-log/dealerships`)
      .then((r) => r.json())
      .then((j) => { if (alive && j && Object.keys(j).length) setDealers(j); })
      .catch(() => { /* keep fallback */ });
    return () => { alive = false; };
  }, []);

  // States from the geo API; the static fallback stays if it fails.
  useEffect(() => {
    let alive = true;
    fetch(GEO_STATES_URL)
      .then((r) => r.json())
      .then((j) => {
        const list: string[] = (j?.data?.states ?? []).map((s: { name: string }) => s.name);
        if (alive && list.length) setStates(list);
      })
      .catch(() => { /* keep fallback */ });
    return () => { alive = false; };
  }, []);

  // Cities for the chosen state — only ever used for dealers we have no city
  // for. Once a dealer knows its own city, that one wins (see the City field).
  useEffect(() => {
    if (!form.state) {
      setCities([]);
      return;
    }
    let alive = true;
    setCitiesLoading(true);
    fetch(GEO_CITIES_URL + encodeURIComponent(form.state))
      .then((r) => r.json())
      .then((j) => {
        if (alive) setCities(Array.isArray(j?.data) ? j.data : []);
      })
      .catch(() => { if (alive) setCities([]); })
      .finally(() => { if (alive) setCitiesLoading(false); });
    return () => { alive = false; };
  }, [form.state]);

  useEffect(() => {
    if (!photo) { setPhotoPreview(null); return; }
    const url = URL.createObjectURL(photo);
    setPhotoPreview(url);
    return () => URL.revokeObjectURL(url);
  }, [photo]);

  const set = (key: keyof FormState, value: string) =>
    setForm((f) => ({ ...f, [key]: value }));

  // Email rides along with the name — never shown, never typed.
  const setSalesperson = (value: string) =>
    setForm((f) => ({ ...f, salesperson: value, email: SALESPERSON_EMAILS[value] ?? "" }));

  // A new State invalidates the City and Dealership picked under the old one.
  const setStateField = (value: string) =>
    setForm((f) => ({ ...f, state: value, city: "", dealership: "" }));

  // MSIL is the odd one out: it gets the Arena/Nexa channel, NOT mats. Every
  // other OEM gets mats and no channel. Clear whichever no longer applies when
  // the OEM changes so a stale value can't ride along.
  const setOem = (value: string) =>
    setForm((f) => ({
      ...f,
      oem: value,
      // Dealers are OEM-specific, so a dealer picked under the old OEM no
      // longer applies — and neither does a city that came from it.
      dealership: "",
      city: "",
      channel: value === MSIL ? f.channel : "",
      mats_sales: value === MSIL ? "" : f.mats_sales,
    }));

  // Photo is Visit-only; drop it if they switch to Calling.
  const setContactMode = (value: string) => {
    setForm((f) => ({ ...f, contact_mode: value }));
    if (value !== "Visit") setPhoto(null);
  };

  const isMsil = form.oem === MSIL;                    // channel field
  const showMats = !!form.oem && !isMsil;              // mats field (all except MSIL)
  const showPhoto = form.contact_mode === "Visit";

  // Dealers depend on BOTH the OEM and the State.
  const dealershipOptions = useMemo(
    () => (form.oem && form.state ? asOptions(dealers[form.oem]?.[form.state] ?? []) : []),
    [dealers, form.oem, form.state],
  );

  // The dropdown works in labels ("NAME — CITY"); the form holds the plain name
  // so the sheet's Dealership column is unchanged.
  const selectedDealer = dealershipOptions.find(
    (o) => o.name === form.dealership && (!form.city || !o.city || o.city === form.city),
  );
  const pickDealer = (label: string) => {
    const o = dealershipOptions.find((x) => dealerLabel(x) === label);
    if (!o) return;
    // A dealer that knows its own city dictates it — that city is the one the
    // OE team's dealer list uses, and matching it is what lets a visit be
    // counted against the right outlet.
    setForm((f) => ({ ...f, dealership: o.name, city: o.city || f.city }));
  };

  // Adds a dealer to the DB master list, then selects it so the rep continues
  // their visit log in one flow — no separate page, no waiting on approval.
  const addDealer = async (name: string, city: string) => {
    const oem = form.oem, state = form.state;
    const body = new FormData();
    body.append("oem", oem);
    body.append("state", state);
    body.append("name", name);
    body.append("city", city);
    body.append("added_by", form.salesperson);
    const res = await fetch(`${API_URL}/visit-log/dealerships`, { method: "POST", body });
    if (!res.ok) throw new Error((await res.json().catch(() => null))?.detail || "Could not add dealership.");
    const saved = await res.json();
    setDealers((d) => {
      const list = asOptions(d[oem]?.[state] ?? []);
      const exists = list.some(
        (o) => o.name.toLowerCase() === saved.name.toLowerCase()
          && o.city.toLowerCase() === (saved.city ?? "").toLowerCase(),
      );
      const next = exists
        ? list
        : [...list, { name: saved.name, city: saved.city ?? "" }]
            .sort((a, b) => dealerLabel(a).localeCompare(dealerLabel(b)));
      return { ...d, [oem]: { ...d[oem], [state]: next } };
    });
    setForm((f) => ({ ...f, dealership: saved.name, city: saved.city || f.city }));
  };

  const toggleRemark = (cat: string) =>
    setRemarks((r) => {
      if (cat in r) {
        const next = { ...r };
        delete next[cat];
        return next;
      }
      return { ...r, [cat]: "" };
    });


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    const missing = REQUIRED.filter((k) => !form[k].trim());
    if (missing.length) {
      setError(`Please fill: ${missing.map((k) => FIELD_LABELS[k]).join(", ")}`);
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }
    // A valid Indian mobile: 10 digits starting 6-9. (Emptiness is caught above.)
    if (!/^[6-9]\d{9}$/.test(form.contact_number)) {
      setError("Contact number must be a 10-digit mobile starting 6–9.");
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }
    if (isMsil && !form.channel) {
      setError("Please select Arena or Nexa.");
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }
    if (showMats && !form.mats_sales.trim()) {
      setError("Please enter Monthly Mats Sales.");
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }
    if (showPhoto && !photo) {
      setError("Please add a photo for a Visit.");
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }
    const chosen = REMARK_CATEGORIES.filter((c) => c in remarks);
    if (chosen.length === 0) {
      setError("Please select at least one remark category.");
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }
    const blank = chosen.filter((c) => !remarks[c].trim());
    if (blank.length) {
      setError(`Please write a remark for: ${blank.join(", ")}`);
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }

    setSubmitting(true);
    try {
      const body = new FormData();
      // Re-stamp the date at submit time — the form may have sat open past midnight.
      Object.entries({ ...form, visit_date: todayISO() }).forEach(([k, v]) =>
        body.append(k, v)
      );
      // Each remark category has its own sheet column, so send them separately
      // (the backend maps by these exact keys). Unselected categories send "".
      REMARK_CATEGORIES.forEach((c) => body.append(`remark_${remarkKey(c)}`, remarks[c] ?? ""));
      if (photo) body.append("photo", photo);

      const res = await fetch(`${API_URL}/visit-log/submit`, { method: "POST", body });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.detail || "Could not submit. Please try again.");
      }
      setSubmitted(true);
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not submit. Check your connection.");
      window.scrollTo({ top: 0, behavior: "smooth" });
    } finally {
      setSubmitting(false);
    }
  };

  const resetForAnother = () => {
    setForm({ ...EMPTY, visit_date: todayISO() });
    setRemarks({});
    setPhoto(null);
    setSubmitted(false);
    setError("");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="min-h-[100dvh] w-full bg-[#faf7f4]">
      <AnimatePresence>{showSplash && <Splash />}</AnimatePresence>

      <div
        className="w-full px-4 py-5 flex flex-col items-center gap-2"
        style={{
          background: "linear-gradient(150deg, #1a1005 0%, #2b1608 55%, #3a1a08 100%)",
          paddingTop: "max(1.25rem, env(safe-area-inset-top))",
        }}
      >
        <img
          src={logoSrc}
          alt="Amato Automotive"
          className="h-8 w-auto"
          style={{ filter: "brightness(0) invert(1)" }}
        />
        <p className="text-[9px] font-bold uppercase tracking-[0.24em] text-white/70 text-center">
          OE Network · Visit / Calling Log
        </p>
      </div>

      <div className="max-w-[560px] mx-auto px-4 py-6 pb-28">
        <AnimatePresence mode="wait">
          {submitted ? (
            <motion.div
              key="done"
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-3xl border border-orange-100 p-8 flex flex-col items-center text-center gap-4"
              style={{ boxShadow: "0 10px 40px rgba(0,0,0,0.04)" }}
            >
              <CheckCircle2 size={44} className="text-green-500" />
              <h2 className="text-lg font-bold text-gray-800">Response recorded</h2>
              <p className="text-sm text-gray-500">Your visit log has been submitted. Thank you.</p>
              <button
                onClick={resetForAnother}
                className="mt-2 h-[52px] px-6 rounded-2xl text-sm font-bold uppercase tracking-wider text-white active:scale-[0.98] transition-transform"
                style={{
                  background: "linear-gradient(135deg, #9B2020, #6B1010)",
                  boxShadow: "0 4px 24px rgba(139, 20, 20, 0.35)",
                }}
              >
                Submit another response
              </button>
            </motion.div>
          ) : (
            <motion.form
              key="form"
              onSubmit={handleSubmit}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: showSplash ? 1.6 : 0, duration: 0.45 }}
              className="bg-white rounded-3xl border border-orange-100 p-5 sm:p-7 flex flex-col gap-7"
              style={{ boxShadow: "0 10px 40px rgba(0,0,0,0.04)" }}
            >
              {error && (
                <motion.div
                  initial={{ opacity: 0, y: -4 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex items-start gap-2 px-3 py-3 rounded-2xl text-sm text-red-600"
                  style={{ background: "rgba(239,68,68,0.07)", border: "1px solid rgba(239,68,68,0.2)" }}
                >
                  <AlertCircle size={16} className="shrink-0 mt-0.5" />
                  <span>{error}</span>
                </motion.div>
              )}

              {/* ── Visit details ── */}
              <Section title="Visit Details" icon={<User size={14} />}>
                <div className="flex flex-col gap-4">
                  <SelectField
                    label={FIELD_LABELS.salesperson}
                    required
                    options={SALESPEOPLE}
                    value={form.salesperson}
                    onChange={setSalesperson}
                  />
                  <SelectField
                    label={FIELD_LABELS.oem}
                    required
                    options={OEMS}
                    value={form.oem}
                    onChange={setOem}
                  />
                  {/* MSIL-only, and asked immediately after the OEM it belongs to. */}
                  <AnimatePresence initial={false}>
                    {isMsil && (
                      <motion.div
                        key="channel"
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        className="flex flex-col gap-2 overflow-hidden"
                      >
                        <Label required>{FIELD_LABELS.channel}</Label>
                        <div className="grid grid-cols-2 gap-2">
                          {MSIL_CHANNELS.map((c) => {
                            const on = form.channel === c;
                            return (
                              <button
                                key={c}
                                type="button"
                                onClick={() => set("channel", on ? "" : c)}
                                className={`h-[52px] px-3 rounded-2xl text-base font-medium border transition-colors flex items-center justify-center gap-2 ${
                                  on
                                    ? "bg-orange-50 border-orange-300 text-orange-700"
                                    : "bg-white border-gray-200 text-gray-600"
                                }`}
                              >
                                {on && <Check size={16} className="text-orange-500" />}
                                {c}
                              </button>
                            );
                          })}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                  <SelectField
                    label={FIELD_LABELS.contact_mode}
                    required
                    options={CONTACT_MODES}
                    value={form.contact_mode}
                    onChange={setContactMode}
                  />
                  {/* Always today — reps log the visit on the day it happened,
                      so the date is fixed rather than pickable. */}
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.visit_date}</Label>
                    <div
                      className="w-full h-[52px] px-4 rounded-2xl text-base bg-gray-50 border border-gray-200 flex items-center gap-2.5 text-gray-700"
                      aria-readonly="true"
                    >
                      <CalendarDays size={16} className="shrink-0 text-gray-400" />
                      <span>{formatDisplayDate(form.visit_date)}</span>
                    </div>
                  </div>
                </div>
              </Section>

              {/* ── Location ── */}
              <Section title="Location" icon={<MapPin size={14} />}>
                <div className="flex flex-col gap-4">
                  <SearchableField
                    label={FIELD_LABELS.state}
                    required
                    options={states}
                    value={form.state}
                    onChange={setStateField}
                    placeholder="Search state…"
                  />
                  {/* Dealership is filtered by OEM + State, and carries its own
                      city where we know it — see the City field below. */}
                  <div>
                    <SearchableField
                      label={FIELD_LABELS.dealership}
                      required
                      options={dealershipOptions.map(dealerLabel)}
                      value={selectedDealer ? dealerLabel(selectedDealer) : form.dealership}
                      onChange={pickDealer}
                      placeholder="Search dealership…"
                      disabled={!form.oem || !form.state}
                      hint={!form.oem ? "Select an OEM first" : "Select a state first"}
                    />
                    {form.oem && form.state && !addingDealer && (
                      <button
                        type="button"
                        onClick={() => setAddingDealer(true)}
                        className="mt-2 flex items-center gap-1.5 text-sm font-semibold text-orange-600 active:text-orange-700"
                      >
                        <Plus size={15} />
                        Add new dealership
                      </button>
                    )}
                    <AnimatePresence>
                      {addingDealer && form.oem && form.state && (
                        <AddDealerPanel
                          oem={form.oem}
                          state={form.state}
                          cities={cities}
                          citiesLoading={citiesLoading}
                          onAdd={addDealer}
                          onClose={() => setAddingDealer(false)}
                        />
                      )}
                    </AnimatePresence>
                  </div>
                  {selectedDealer?.city ? (
                    <DerivedCity city={selectedDealer.city} />
                  ) : (
                    <SearchableField
                      label={FIELD_LABELS.city}
                      required
                      options={cities}
                      value={form.city}
                      onChange={(v) => set("city", v)}
                      placeholder="Search city…"
                      disabled={!form.state}
                      hint="Select a state first"
                      loading={citiesLoading}
                    />
                  )}
                </div>
              </Section>

              {/* ── Dealership details ── */}
              <Section title="Dealership" icon={<Building2 size={14} />}>
                <div className="flex flex-col gap-4">
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.address}</Label>
                    <textarea
                      rows={2}
                      className={areaBase}
                      value={form.address}
                      onChange={(e) => set("address", e.target.value)}
                      placeholder="Dealership address"
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.contact_person}</Label>
                    <textarea
                      rows={2}
                      className={areaBase}
                      value={form.contact_person}
                      onChange={(e) => set("contact_person", e.target.value)}
                      placeholder="Person met"
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.contact_number}</Label>
                    <input
                      type="tel"
                      inputMode="numeric"
                      maxLength={10}
                      className={fieldBase}
                      value={form.contact_number}
                      onChange={(e) => set("contact_number", e.target.value.replace(/\D/g, ""))}
                      placeholder="10-digit mobile number"
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.designation}</Label>
                    <textarea
                      rows={2}
                      className={areaBase}
                      value={form.designation}
                      onChange={(e) => set("designation", e.target.value)}
                      placeholder="Their designation"
                    />
                  </div>
                </div>
              </Section>

              {/* ── Monthly figures ── */}
              <Section title="Dealer's Monthly Figures" icon={<TrendingUp size={14} />}>
                <div className="flex flex-col gap-4">
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.car_sales}</Label>
                    <input
                      type="number" inputMode="numeric" min="0"
                      className={fieldBase}
                      value={form.car_sales}
                      onChange={(e) => set("car_sales", e.target.value)}
                      placeholder="0"
                    />
                  </div>
                  <div className="flex flex-col gap-2">
                    <Label required>{FIELD_LABELS.seat_cover_sales}</Label>
                    <input
                      type="number" inputMode="numeric" min="0"
                      className={fieldBase}
                      value={form.seat_cover_sales}
                      onChange={(e) => set("seat_cover_sales", e.target.value)}
                      placeholder="0"
                    />
                  </div>
                  {/* Mats is for every OEM except MSIL. */}
                  <AnimatePresence initial={false}>
                    {showMats && (
                      <motion.div
                        key="mats"
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        className="flex flex-col gap-2 overflow-hidden"
                      >
                        <Label required>{FIELD_LABELS.mats_sales}</Label>
                        <input
                          type="number" inputMode="numeric" min="0"
                          className={fieldBase}
                          value={form.mats_sales}
                          onChange={(e) => set("mats_sales", e.target.value)}
                          placeholder="0"
                        />
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </Section>

              {/* ── Remarks: pick categories, each opens its own note ── */}
              <Section title="Remarks" icon={<MessageSquare size={14} />}>
                <div className="flex flex-col gap-3">
                  <Label required>Remark Category</Label>
                  <div className="grid grid-cols-2 gap-2">
                    {REMARK_CATEGORIES.map((cat) => {
                      const on = cat in remarks;
                      return (
                        <button
                          key={cat}
                          type="button"
                          onClick={() => toggleRemark(cat)}
                          className={`h-[52px] px-3 rounded-2xl text-sm font-medium border transition-colors ${
                            on
                              ? "bg-orange-50 border-orange-300 text-orange-700"
                              : "bg-white border-gray-200 text-gray-600"
                          }`}
                        >
                          {cat}
                        </button>
                      );
                    })}
                  </div>

                  <AnimatePresence initial={false}>
                    {REMARK_CATEGORIES.filter((c) => c in remarks).map((cat) => (
                      <motion.div
                        key={cat}
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        className="flex flex-col gap-2 overflow-hidden"
                      >
                        <Label required>{cat}</Label>
                        <textarea
                          rows={3}
                          className={areaBase}
                          value={remarks[cat]}
                          onChange={(e) =>
                            setRemarks((r) => ({ ...r, [cat]: e.target.value }))
                          }
                          placeholder={`Notes on ${cat.toLowerCase()}…`}
                        />
                      </motion.div>
                    ))}
                  </AnimatePresence>
                </div>
              </Section>

              {/* ── Photo: Visit only, gallery only ── */}
              <AnimatePresence initial={false}>
                {showPhoto && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    className="overflow-hidden"
                  >
                    <Section title="Photo *" icon={<ImagePlus size={14} />}>
                      {photoPreview ? (
                        <div className="relative rounded-2xl overflow-hidden border border-gray-200">
                          <img src={photoPreview} alt="Selected" className="w-full max-h-72 object-cover" />
                          <button
                            type="button"
                            onClick={() => setPhoto(null)}
                            className="absolute top-2 right-2 h-10 w-10 rounded-full bg-black/60 text-white flex items-center justify-center active:bg-black/80"
                            aria-label="Remove photo"
                          >
                            <X size={18} />
                          </button>
                        </div>
                      ) : (
                        <label className="flex flex-col items-center justify-center gap-2 h-32 rounded-2xl border-2 border-dashed border-gray-200 active:border-orange-300 active:bg-orange-50/40 transition-colors cursor-pointer">
                          <ImagePlus size={22} className="text-gray-400" />
                          <span className="text-sm text-gray-500 font-medium">Choose from gallery</span>
                          <input
                            type="file"
                            accept="image/*"
                            className="hidden"
                            onChange={(e) => setPhoto(e.target.files?.[0] ?? null)}
                          />
                        </label>
                      )}
                    </Section>
                  </motion.div>
                )}
              </AnimatePresence>

              <p className="text-center text-[10px] text-gray-400 uppercase tracking-wider">
                © {new Date().getFullYear()} Amato Automotive
              </p>
            </motion.form>
          )}
        </AnimatePresence>
      </div>

      {!submitted && (
        <div
          className="fixed bottom-0 left-0 right-0 px-4 pt-3 border-t border-orange-100 bg-white/95 backdrop-blur"
          style={{ paddingBottom: "max(0.75rem, env(safe-area-inset-bottom))" }}
        >
          <div className="max-w-[560px] mx-auto">
            <button
              type="submit"
              onClick={handleSubmit}
              disabled={submitting}
              className="w-full h-[52px] rounded-2xl text-sm font-bold uppercase tracking-wider text-white disabled:opacity-60 flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                background: submitting
                  ? "rgba(139, 28, 28, 0.5)"
                  : "linear-gradient(135deg, #9B2020, #6B1010)",
                boxShadow: submitting ? "none" : "0 4px 24px rgba(139, 20, 20, 0.35)",
              }}
            >
              {submitting ? (
                <><Loader2 size={16} className="animate-spin" />Submitting…</>
              ) : (
                <><Send size={15} />Submit</>
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
